### ISSUE TITLE
Python add region

### ISSUE THREAD

**Issue by olds463** [jparnaudeau/terraform-aws-ssm-patch-management#10]
Hello,

FYI Looks like based on my prior issue #6 , you need to pass the AWS CLI profile and region to the python script as arguments for registering the default baseline. It assumes the profile of your AWS credentials and if you specify your region here, it is what will be used. 

Right now while running multiple regions, the created baseline does not get set as default to an alternate region under the same AWS account.

**Comment by jparnaudeau** [comment]
Hi olds463,
thank you so much for your's "eagle eyes" !
I have just publish a new version ` 1.1.1` to propagate the region on the python script for the default patch baseline registration.
Unfortunatelly, you should have to remove in your tfstate the corresponding "null_ressource" because i have introduced the region in the trigger map of the null_resource and terraform raise an error.
I have push as well a new simple example for multi-region deployment for the patch baseline.
Jerome.

**Comment by olds463** [comment]
Thanks for the fix! I think you should also add the AWS profile. If you use terraform workspaces with multiple AWS accounts (ie: dev/test/stage/prod) then you'll have multiple profiles in ~/.aws/credentials. This python helper will just use the [default] every time.

**Comment by jparnaudeau** [comment]
Hi,
Hmm, I don't use terraform workspaces often: I'm not sure about my fix. I have published version `1.1.1-with-profile`. Say me if it's ok for you. If it's ok i will publish a new official version.

**Comment by olds463** [comment]
Works great! Can apply and destroy successfully, and baseline gets registered correctly across profiles.

**Comment by jparnaudeau** [comment]
Cool. version 1.1.2 is published.
